project_id = "pwhdztynilndcxruezjo"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-cancellation-email]
verify_jwt = false

[functions.send-booking-reminder]
verify_jwt = false

[functions.vehicle-control]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false
