project_id = "pwhdztynilndcxruezjo"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-cancellation-email]
verify_jwt = false

[functions.send-booking-reminder]
verify_jwt = false
